### PR TITLE
hasura-cli@v2.x.y docker image

### PR DESCRIPTION
**Pull request by evityuk**
@dvasdekis 
Please publish Docker image v2.4.0 to dockerhub with this changes

Changes:
 - Use stable branch for cli@2.X.X installation in order to use recent/latest cli version in image. See [README.md](https://github.com/hasura/graphql-engine/tree/master/cli#download-graphql-engine-cli-bundled-with-hasura-cli)/[Docs](https://hasura.io/docs/latest/graphql/core/hasura-cli/install-hasura-cli/#install-a-binary-globally) for reference.
 - update README.md: update versions/links+provide init example.

### CODE REVIEW

**Comment by evityuk** [comment]
@dvasdekis 
Thanks in advance for review/merge.

**Comment by dvasdekis** [comment]
Thanks for contributing!

**Comment by evityuk** [comment]
Currently install script relies on default VERSION=2.4.0.
In order to be able to pull image with this tag from hub.docker.com registry
`docker pull dvasdekis/hasura-cli-docker:2.4.0`
and with backward compatibility(eg: for existing 'docker pull .../hasura-cli:**latest**)
it make sense to:
 - add tag:1.3.3 to current docker image
 - add tag:2.4.0 to updated docker image 
and publish both.

Also regarding forward compatibility: it make sense to add 
 ```
 env VERSION
 ...
 /bin/sh -c curl ... | INSTALL_PATH=/hasuracli VERSION=$VERSION bash
 ``` 
to Dockerfile to prevent future breaking changes(eg: with update to 3.0.0 of stable installer script

**Comment by dvasdekis** [comment]
I don't actively use this any more as I have switched to Hasura Cloud, so if you would like to take over maintenance, I will move this repo to your ownership.

**Pull request merged**
